# Serena Project Configuration for pokeseal
# https://oraios.github.io/serena/02-usage/050_configuration.html

# Programming language of the project
language: typescript

# Whether to use the project's gitignore file to ignore files
ignore_all_files_in_gitignore: true

# List of additional paths to ignore (same syntax as gitignore)
ignored_paths:
  - node_modules
  - .next
  - dist
  - build
  - "*.lock"

# Whether the project is in read-only mode
read_only: false
